import Head from "next/head";
import MainCarousel from "@/components/MainCarousel";
import logger from "@/helpers/logger";
import { createClient } from "./api/client";

const contentStyle = {
  width: "100%",
  height: "100%",
};

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Allison&family=Montserrat:wght@100&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div style={contentStyle}>
        <MainCarousel data={data} />
      </div>
    </>
  );
}

Home.layout = "web";

export const getServerSideProps = async () => {
  try {
    const client = createClient();
    const res = await client.get("/carousel");
    const data = res.data;
    return { props: { data } };
  } catch (error) {
    logger.error(`AdminHome:${error}`);
  }
};
