import { Layout } from "antd";
import React, { useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";

const SideBar = dynamic(() => import("./SideBar/SideBar"));
const NavBar = dynamic(() => import("./Navbar/Navbar"));
const ContentWrapper = dynamic(() => import("./ContentWrapper/ContentWrapper"));
function AdminLayout({ children }) {
  const [collapsed, setCollapsed] = useState(false);
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SideBar collapsed={collapsed}></SideBar>
        <Layout>
          <NavBar collapseAction={() => setCollapsed(!collapsed)} />
          <ContentWrapper>{children}</ContentWrapper>
        </Layout>
      </Layout>
    </>
  );
}
export default AdminLayout;
